name: Test chill-viking/dotnet-sonar-scanner

on:
  workflow_dispatch:
    inputs:
      pool:
        description: 'Pool to run on'
        required: true
        default: 'windows-latest'
        type: choice
        options:
        - windows-latest
        - ubuntu-latest

jobs:
  test_and_report_coverage:
    runs-on: ${{ inputs.pool }}
    name: use chill-viking/dotnet-sonar-scanner
    steps:
      - uses: chill-viking/dotnet-sonar-scanner@v1.0.0
        name: use composite action
        with:
          sonar-project-key: 'chill-viking-org_github-actions-tests-dotnet-sonar-scanner'
          sonar-org-key: 'chill-viking-org'
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_DOTNET }}
          project-version: '1.0.0-alpha'
          working-directory: './dotnet-sonar-scanner'
